title: Laura Paulino
logo: /assets/img/headshot_circle.png
description: Technical Skills: Industrial KPI, Process Mapping, Continuous Improvement, Power BI
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
